### PR TITLE
Added Icons

### PR DESCRIPTION
**Pull request by morganb21**
Hello,

What do you think about adding icons to the featurescripts?

### CODE REVIEW

**Comment by dcowden** [comment]
I feel like icons will need to be a bit larger to be valuable. Ideally, the icons always come from a screenshot of the feature in use, like on the onshape site.

  I also think that we should move to Jekyll before we add images.  Editing a simple link is not too bad, but once we have images and text, we need a stronger solution to present well on multiple screen sizes, and ability to show images in a larger window.

Are you familiar with Jekyll?

**Comment by morganb21** [comment]
@dcowden 
I am not familiar with Jekyll
Have you heard of [Bubble](http://bubble.is)?
With the icons, I was thinking of having icons like what we could get to appear on the feature if this [Feature request](https://forum.onshape.com/discussion/8169/featurescript-custom-icons) gets implemented.

**Comment by dcowden** [comment]
Not familiar with bubble. Though I must confess having seen several visual programming tools over the years I have never liked them. You always eventually run into limitations.

Jekyll is an automated static site generator designed to publish websites for bloggers. It powers GitHub pages, and would be a perfect fit for our project here.

**Comment by dcowden** [comment]
@morganb21 ah! now that i've seen your feature request in onshape about icons, i understand your point more clearly.  

If onshape supports icons in the GUI, then clearly it would be valuable to show them in our list. However, i still think there would be additional value in showing a real-life picture in action. We need both.

I think this points even more to using a more complex layout tool, so that we can support both without a really complex layout we have to manually maintain.

I think the fields we are up to include:
   * name
   * link
   * description
   * author
   * company
   * screenshot
   * icon

**Comment by emagdalenaC2i** [comment]
Other fields that could be included:

- Author email
- Company website
- Last version number

**Comment by dcowden** [comment]
yes very good points-- i agree with all of those.

**Comment by morganb21** [comment]
Sorry, I accidentally merged

**Comment by morganb21** [comment]
@dcowden 
I have made a featurescripts website using Bubble [here](https://featurescripts.bubbleapps.io/).
Please tell me what you think of it.

**Comment by dcowden** [comment]
ok thanks i'll give it a try!

**Pull request merged**
