### PR TITLE
(IMP) Add Author and Company

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
I think it could be a good idea to include the author and company of the scripts.

Tell me your opinion about the best format. I have used:
Company_name (CompanyWebSite): Author <AuthorEmail>

**Comment by dcowden** [comment]
@emagdalenaC2i  Hi, and Welcome!

I definitely agree with this idea. One other thing i've learned from the community is that we'd like to have images as well-- many times, that goes a long way towards communicating what the FS does.

I dont' want to just 'add columns'  to the list, though.  Once we have author, name, company, website, and images, we have what's really a product listing.  To handle that and still present well, i'd like to move to a jekyl based site.

**Comment by emagdalenaC2i** [comment]
Sound great

Please, tell me if I can help

**Comment by morganb21** [comment]
@emagdalenaC2i 
I was thinking of having it link to their Onshape forum profile.
Would that be alright?

**Comment by emagdalenaC2i** [comment]
It works for me anyway you want.
I would prefer to add the author name and email and the company name and website (if there is a company involved). This is how I do in other open source projects in which I collaborate.
But the link to the users profile in Onshape is ok for me.

**Comment by dcowden** [comment]
I would prefer not to to make these changes in a 'plain-text' kind of way. I think the extra information is useful, but i'd rather move to jekyl so that we can do the layout justice.

**Comment by emagdalenaC2i** [comment]
Ok, that's fine

You can close this PR if you want

**Comment by dcowden** [comment]
On the contrary, i'd like to keep it open, but implment it with a really good solution....

**Comment by dcowden** [comment]
something simple like this site might be good:
http://www.jekyll-plugins.com/

**Comment by dcowden** [comment]
there is some relevant discussion going on in #22.  Its also recommending adding another field, contributing to the idea that we need to move to a site generator for all the fields we'd be maintaining.

**Pull request closed without merging**
